name: udev
version: 0.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  ffi: ^2.0.1
  meta: ^1.7.0

dev_dependencies:
  ffigen: ^6.0.1
  lints: ^2.0.0
  mockito: ^5.2.0
  test: ^1.17.7
